[build]
  command = "npm ci && npm run build"
  publish = "dist"
  functions = "netlify/functions"


[functions]
  included_files = ["node_modules/**/*"]
  node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[dev]
  command = "npm run dev"
  targetPort = 5173
  publish = "dist"
  functionsPort = 9999
  autoLaunch = true

